./cminor -scan good0.cminor
./cminor -scan good1.cminor
./cminor -scan good2.cminor
./cminor -scan good3.cminor
./cminor -scan good4.cminor
./cminor -scan good5.cminor
./cminor -scan good6.cminor
./cminor -scan good7.cminor
./cminor -scan good8.cminor
./cminor -scan good9.cminor
./cminor -scan bad0.cminor
./cminor -scan bad1.cminor
./cminor -scan bad2.cminor
./cminor -scan bad3.cminor
./cminor -scan bad4.cminor
./cminor -scan bad5.cminor
./cminor -scan bad6.cminor
./cminor -scan bad7.cminor
./cminor -scan bad8.cminor
./cminor -scan bad9.cminor
